<?php

// Include DatabaseHelper.php file
require_once('DatabaseHelper.php');

// Instantiate DatabaseHelper class
$database = new DatabaseHelper();

// Get parameters from GET Request
// Btw. you can see the parameters in the URL if they are set
$INGREDIENTID = '';
if (isset($_GET['INGREDIENTID'])) {
    $INGREDIENTID = $_GET['INGREDIENTID'];
}

$INGREDIENTNAME = '';
if (isset($_GET['INGREDIENTNAME '])) {
    $INGREDIENTNAME = $_GET['INGREDIENTNAME '];
}

$INGREDIENTTYPE = '';
if (isset($_GET['INGREDIENTTYPE'])) {
    $INGREDIENTTYPE = $_GET['INGREDIENTTYPE'];
}

//Fetch data from database
$ingredient_array = $database->selectFromINGREDIENTWhere($INGREDIENTID, $INGREDIENTNAME, $INGREDIENTTYPE);
?>

<?php

// Include DatabaseHelper.php file
require_once('DatabaseHelper.php');

// Instantiate DatabaseHelper class
$database = new DatabaseHelper();

// Get parameters from GET Request
// Btw. you can see the parameters in the URL if they are set
$ALLERGYID = '';
if (isset($_GET['ALLERGYID'])) {
    $ALLERGYID = $_GET['ALLERGYID'];
}

$INTOLLERANCE = '';
if (isset($_GET['INTOLLERANCE '])) {
    $INTOLLERANCE = $_GET['INTOLLERANCE '];
}

$ALLERGYDESCRIPTION = '';
if (isset($_GET['ALLERGYDESCRIPTION'])) {
    $ALLERGYDESCRIPTION = $_GET['ALLERGYDESCRIPTION'];
}

//Fetch data from database
$allergy_array = $database->selectFromALLERGYWhere($ALLERGYID, $INTOLLERANCE, $ALLERGYDESCRIPTION);
?>

<?php

// Include DatabaseHelper.php file
require_once('DatabaseHelper.php');

// Instantiate DatabaseHelper class
$database = new DatabaseHelper();

// Get parameters from GET Request
// Btw. you can see the parameters in the URL if they are set
$DIETID = '';
if (isset($_GET['DIETID'])) {
    $DIETID = $_GET['DIETID'];
}

$DIETNAME = '';
if (isset($_GET['DIETNAME'])) {
    $DIETNAME = $_GET['DIETNAME'];
}

$DIETDESCRIPTION = '';
if (isset($_GET['DIETDESCRIPTION'])) {
    $DIETDESCRIPTION = $_GET['DIETDESCRIPTION'];
}

//Fetch data from database
$diet_array = $database->selectFromDIETWhere($DIETID, $DIETNAME, $DIETDESCRIPTION);
?>

<?php

// Include DatabaseHelper.php file
require_once('DatabaseHelper.php');

// Instantiate DatabaseHelper class
$database = new DatabaseHelper();

// Get parameters from GET Request
// Btw. you can see the parameters in the URL if they are set
$RECIPEID = '';
if (isset($_GET['RECIPEID'])) {
    $RECIPEID = $_GET['RECIPEID'];
}

$RECIPENAME = '';
if (isset($_GET['RECIPENAME'])) {
    $RECIPENAME = $_GET['RECIPENAME'];
}

$RECIPEDESCRIPTION = '';
if (isset($_GET['RECIPEDESCRIPTION'])) {
    $RECIPEDESCRIPTION = $_GET['RECIPEDESCRIPTION'];
}

//Fetch data from database
$recipe_array = $database->selectFromRecipeWhere($RECIPEID, $RECIPENAME, $RECIPEDESCRIPTION);
?>

<?php

// Include DatabaseHelper.php file
require_once('DatabaseHelper.php');

// Instantiate DatabaseHelper class
$database = new DatabaseHelper();
// get parameters from get request user profiles
$USERID = '';
if (isset($_GET['USERID'])) {
    $USERID = $_GET['USERID'];
}

$USERFIRSTNAME = '';
if (isset($_GET['USERFIRSTNAME'])) {
    $USERFIRSTNAME = $_GET['USERFIRSTNAME'];
}

$USERLASTNAME = '';
if (isset($_GET['USERLASTNAME'])) {
    $USERLASTNAME = $_GET['USERLASTNAME'];
}


$user_array = $database->selectFromUSERPROFILEWhere($USERID, $USERFIRSTNAME, $USERLASTNAME);
?>


<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>immerjung</title>
    <link rel="stylesheet" type="text/css" href="MyCssFile.css">
</head>

<body style="color:DimGray;">


<br>
<h1 style="color:DimGray;">immerjung</h1>
<h2 style="color:DimGray;">für deine Umwelt und mehr Gesundheit durch bewusstes Kochen<h2>
  <img src="header.jpg"

<!-- Add Person -->
<h2>Rezept hinzufügen: </h2>
<form method="post" action="addrecipe.php">
    <!-- Person ID is not needed, because its autogenerated by the database -->

    <!-- Name textbox -->
    <div>
        <label for="new_RECIPENAME">Rezeptname:</label>
        <input id="new_RECIPENAME" name="RECIPENAME" type="text" maxlength="255">
    </div>
    <br>

    <!-- Description textbox -->
    <div>
        <label for="new_RECIPEDESCRIPTION">Rezeptbeschreibung:</label>
        <input id="new_RECIPEDESCRIPTION" name="RECIPEDESCRIPTION" type="text" maxlength="500">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit">
            Rezept hinzufügen
        </button>
    </div>
</form>
<br>
<hr>

<!-- Delete Person -->
<h2>Rezept entfernen: </h2>
<form method="post" action="delrecipe.php">
    <!-- ID textbox -->
    <div>
        <label for="del_RECIPEID">ID:</label>
        <input id="del_RECIPEID" name="RECIPEID" type="number" min="0">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit">
            Rezept entfernen
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search form -->
<h2>Rezept Suche:</h2>
<form method="get">
    <!-- ID textbox:-->
    <div>
        <label for="RECIPEID">ID:</label>
        <input id="RECIPEID" name="RECIPEID" type="number" value='<?php echo $RECIPEID; ?>' min="0">
    </div>
    <br>

    <!-- Name textbox:-->
    <div>
        <label for="RECIPENAME">Rezeptname:</label>
        <input id="RECIPENAME" name="RECIPENAME" type="text" class="form-control input-md" value='<?php echo $RECIPENAME; ?>'
               maxlength="20">
    </div>
    <br>

    <!-- Surname textbox:-->
    <div>
        <label for="RECIPEDESCRIPTION">Rezeptbeschreibung:</label>
        <input id="RECIPEDESCRIPTION" name="RECIPEDESCRIPTION" type="text"
               value='<?php echo $RECIPEDESCRIPTION; ?>' maxlength="500">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button id='submit' type='submit'>
            Search
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search result -->
<h2>Ergebnis der Rezeptesuche:</h2>
<table>
    <tr>
        <th>ID</th>
        <th>Rezeptname</th>
        <th>Rezeptbeschreibung</th>
    </tr>
    <?php foreach ($recipe_array as $recipe) : ?>
        <tr>
            <td><?php echo $recipe['RECIPEID']; ?>  </td>
            <td><?php echo $recipe['RECIPENAME']; ?>  </td>
            <td><?php echo $recipe['RECIPEDESCRIPTION']; ?>  </td>
        </tr>
    <?php endforeach; ?>
</table>
  <br>

  <h2>Lebensmittel:</h2>
  <table>
      <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Typ</th>
      </tr>
      <?php foreach ($ingredient_array as $ingredient) : ?>
          <tr>
              <td><?php echo $ingredient['INGREDIENTID']; ?>  </td>
              <td><?php echo $ingredient['INGREDIENTNAME']; ?>  </td>
              <td><?php echo $ingredient['INGREDIENTTYPE']; ?>  </td>
          </tr>
      <?php endforeach; ?>
  </table>
    <br>



<h2>Wählbare Allergien:</h2>
<table>
    <tr>
        <th>ID</th>
        <th>Intolleranz</th>
        <th>Beschreibung</th>
    </tr>
    <?php foreach ($allergy_array as $allergy) : ?>
        <tr>
            <td><?php echo $allergy['ALLERGYID']; ?>  </td>
            <td><?php echo $allergy['INTOLLERANCE']; ?>  </td>
            <td><?php echo $allergy['ALLERGYDESCRIPTION']; ?>  </td>
        </tr>
    <?php endforeach; ?>
</table>
  <br>

<h2>Vertrenene Küchen:</h2>
<table>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Beschreibung</th>
    </tr>
    <?php foreach ($diet_array as $diet) : ?>
        <tr>
            <td><?php echo $diet['DIETID']; ?>  </td>
            <td><?php echo $diet['DIETNAME']; ?>  </td>
            <td><?php echo $diet['DIETDESCRIPTION']; ?>  </td>
        </tr>
    <?php endforeach; ?>
</table>
  <br>


<h2>Nutzer der App:</h2>
<table>
    <tr>
        <th>ID</th>
        <th>Vorname</th>
        <th>Nachname</th>
    </tr>
    <?php foreach ($user_array as $user) : ?>
        <tr>
            <td><?php echo $user['USERID']; ?>  </td>
            <td><?php echo $user['USERFIRSTNAME']; ?>  </td>
            <td><?php echo $user['USERLASTNAME']; ?>  </td>
        </tr>
    <?php endforeach; ?>
</table>
  <br>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>
