DROP TABLE RECIPE CASCADE CONSTRAINTS;
DROP TABLE INGREDIENT CASCADE CONSTRAINTS;
DROP TABLE ALLERGY CASCADE CONSTRAINTS;
DROP TABLE UUSER CASCADE CONSTRAINTS;
DROP TABLE MEDICALHEALTHBENEFIT CASCADE CONSTRAINTS;
DROP TABLE SEASONALITY CASCADE CONSTRAINTS;
DROP TABLE REGIONALITY CASCADE CONSTRAINTS;
DROP TABLE AYURVEDIC CASCADE CONSTRAINTS;
DROP TABLE HAS CASCADE CONSTRAINTS;
DROP TABLE HASMANY CASCADE CONSTRAINTS;
DROP TABLE SELECTSMANY CASCADE CONSTRAINTS;
DROP TABLE HASSEVERAL CASCADE CONSTRAINTS;

DROP SEQUENCE RID_SEQ;
DROP SEQUENCE SEASONALITYID_SEQ;
DROP SEQUENCE REGIONALITYID_SEQ;
DROP PROCEDURE RDELETERECIPE;
DROP TRIGGER RID_TRIGGER;
DROP TRIGGER SEASONALITYID_TRIGGER;
DROP TRIGGER REGIONALITYID_SEQ;


select * from User_tables;
select * from User_sequences;









